{
 "title": "Team8",
 "description": "DIY a simple weather station using a Raspberry Pi Zero W and a DHT22 temperature/humidity sensor.\r\n\r\nMore docs coming soon.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Bucket", "query": "buckets()" }
  ]
 },
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_measure\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_measure\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\r\n"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_measure\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hum\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_measure\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hum\")\r\n"
    }
   ]
  }
 ]
}